// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.5
// source: common/permission.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 数据权限
type DataPermission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 组织编码列表 用','隔开
	OrgCodes string `protobuf:"bytes,1,opt,name=org_codes,json=orgCodes,proto3" json:"org_codes,omitempty"`
	// 大区编号列表 用','隔开
	BigAreas string `protobuf:"bytes,2,opt,name=big_areas,json=bigAreas,proto3" json:"big_areas,omitempty"`
	// 用户id
	MemberId string `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	// 医生id
	DoctorCode string `protobuf:"bytes,4,opt,name=doctor_code,json=doctorCode,proto3" json:"doctor_code,omitempty"`
}

func (x *DataPermission) Reset() {
	*x = DataPermission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_permission_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPermission) ProtoMessage() {}

func (x *DataPermission) ProtoReflect() protoreflect.Message {
	mi := &file_common_permission_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPermission.ProtoReflect.Descriptor instead.
func (*DataPermission) Descriptor() ([]byte, []int) {
	return file_common_permission_proto_rawDescGZIP(), []int{0}
}

func (x *DataPermission) GetOrgCodes() string {
	if x != nil {
		return x.OrgCodes
	}
	return ""
}

func (x *DataPermission) GetBigAreas() string {
	if x != nil {
		return x.BigAreas
	}
	return ""
}

func (x *DataPermission) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *DataPermission) GetDoctorCode() string {
	if x != nil {
		return x.DoctorCode
	}
	return ""
}

var File_common_permission_proto protoreflect.FileDescriptor

var file_common_permission_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x22, 0x88, 0x01, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x72, 0x67, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x67, 0x43, 0x6f, 0x64, 0x65,
	0x73, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x69, 0x67, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x69, 0x67, 0x41, 0x72, 0x65, 0x61, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_permission_proto_rawDescOnce sync.Once
	file_common_permission_proto_rawDescData = file_common_permission_proto_rawDesc
)

func file_common_permission_proto_rawDescGZIP() []byte {
	file_common_permission_proto_rawDescOnce.Do(func() {
		file_common_permission_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_permission_proto_rawDescData)
	})
	return file_common_permission_proto_rawDescData
}

var file_common_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_permission_proto_goTypes = []interface{}{
	(*DataPermission)(nil), // 0: common.DataPermission
}
var file_common_permission_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_permission_proto_init() }
func file_common_permission_proto_init() {
	if File_common_permission_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_permission_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataPermission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_permission_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_permission_proto_goTypes,
		DependencyIndexes: file_common_permission_proto_depIdxs,
		MessageInfos:      file_common_permission_proto_msgTypes,
	}.Build()
	File_common_permission_proto = out.File
	file_common_permission_proto_rawDesc = nil
	file_common_permission_proto_goTypes = nil
	file_common_permission_proto_depIdxs = nil
}
